services:
  reviewnest:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    restart: always
    env_file: .env
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    container_name: db
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - db_data:/data/db

volumes:
  db_data:
